name: Renovatebot - Trigger integration tests on PR update

on:
  pull_request:
    branches:
    - 'renovate/**'
  push:
    branches:
    - 'renovate/**'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post a comment
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const comment = "/it-go";
            github.rest.issues.createComment({
              ...context.repo,
              issue_number,
              body: comment
            });
